# Site settings
title: LucasTafarelBS :)
email: lucastafarelbs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website pessoal para retribuir à comunidade com um pouco dos conhecimentos adquiridos nela :)
baseurl: ""
url: "lucastafarelbs.github.io" # the base hostname & protocol for your site
twitter_username: lucastafarelbs
github_username:  lucastafarelbs
facebook_username: lucastafarelbs

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# exclude
exclude: [node_modules","package.json"]
